
###
GET http://localhost:3000/orders/a03b7801-d6d9-456d-ba3e-0e73750bc6b2

###
POST http://localhost:3000/orders
Content-Type: application/json

{
  "userId": "70e1e61d-f2ae-4d7d-bf8f-d65eafdb6a45",
  "orderItems": [
    {
      "productId": "1e112c02-7c92-4d52-b76e-485e41e3f64d",
      "unitPrice": 59000,
      "quantity": 1
    },
    {
      "productId": "f751e63f-686d-42d4-898e-3ef6d4137908",
      "unitPrice": 79000,
      "quantity": 2
    }
  ]
}
