###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/?offset=0&limit=2&order=newest

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "code@gmail.com",
  "firstName": "code",
  "lastName": "it",
  "address": "서울시"
}

###
PATCH http://localhost:3000/users/5ce4b6ee-5541-432d-b0e5-bd8c7324fb48
Content-Type: application/json

{
  "email": "update@gmail.com",
  "firstName": "up",
  "lastName": "date",
  "address": "부산광역시"
}


###
DELETE http://localhost:3000/users/5ce4b6ee-5541-432d-b0e5-bd8c7324fb48
Content-Type: application/json





###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/?order=priceLowest&category=FASHION
Content-Type: application/json

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name":""",    
  "description":"",
  "price":1500000,
  "stock":1,
  "category":"FASHION"
}

###
DELETE http://localhost:3000/products/3cd8ba61-ecc4-461c-9b12-5f9489333aac
Content-Type: application/json